### ISSUE TITLE
how to maintain the reusable code (computation logic) in screenplay

### ISSUE THREAD

**Issue by InduKrish** [testla-project/testla-screenplay-playwright-js#40]
I do have a test that uses a set of reusable methods -some computation logic , where i can place the logic that will be used across all my other tests? 

Not sure if i should place inside BrowseTheWeb, - but it is 10-15 lines of code- computation logic .. Should i build a new Util class that move all reusable methods to the util class? can you please advise?

**Comment by kbrueckner** [comment]
That depends a little on the type of the code. Usually you would not call any "helper code" directly in a test but wrap that instead into an action which is triggered by an actor. Actors do not necessarily need to be "real users" but could in my view also be system users or similars.

I advise not to put it inside BrowseTheWeb but write a custom action which makes use of BrowseTheWeb. If your logic does not rely on the page object from playwright the custom action could be a stand alone one without need of an ability.

Can you maybe share that code which we are talking about, so that it is easier to make an appropriate suggestion :)

**Comment by munichbughunter** [comment]
Inactive for a certain period of time!
